[package]
name = "fagman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniquad = "0.4.0-alpha"
fontdue = "0.5.2"
image = "0.24"

